// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2  - DO NOT EDIT.

package todos

import (
	go_context "context"
	go_net_http "net/http"

	gotsrpc "github.com/foomo/gotsrpc/v2"
	pkg_errors "github.com/pkg/errors"
)

type ServiceGoTSRPCClient interface {
	CreateTodo(ctx go_context.Context, text string) (todos Todos, err *Error, clientErr error)
	DeleteTodo(ctx go_context.Context, ID TodoID) (todos Todos, err *Error, clientErr error)
	GetTodos(ctx go_context.Context) (todos Todos, err *Error, clientErr error)
	SetComplete(ctx go_context.Context, ID TodoID, complete bool) (todos Todos, err *Error, clientErr error)
}

type HTTPServiceGoTSRPCClient struct {
	URL      string
	EndPoint string
	Client   gotsrpc.Client
}

func NewDefaultServiceGoTSRPCClient(url string) *HTTPServiceGoTSRPCClient {
	return NewServiceGoTSRPCClient(url, "/services/todos")
}

func NewServiceGoTSRPCClient(url string, endpoint string) *HTTPServiceGoTSRPCClient {
	return NewServiceGoTSRPCClientWithClient(url, endpoint, nil)
}

func NewServiceGoTSRPCClientWithClient(url string, endpoint string, client *go_net_http.Client) *HTTPServiceGoTSRPCClient {
	return &HTTPServiceGoTSRPCClient{
		URL:      url,
		EndPoint: endpoint,
		Client:   gotsrpc.NewClientWithHttpClient(client),
	}
}

func (tsc *HTTPServiceGoTSRPCClient) CreateTodo(ctx go_context.Context, text string) (todos Todos, err *Error, clientErr error) {
	rpcArgs := []any{text}
	rpcReply := []any{&todos, &err}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "CreateTodo", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call todos.ServiceGoTSRPCProxy CreateTodo")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) DeleteTodo(ctx go_context.Context, ID TodoID) (todos Todos, err *Error, clientErr error) {
	rpcArgs := []any{ID}
	rpcReply := []any{&todos, &err}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "DeleteTodo", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call todos.ServiceGoTSRPCProxy DeleteTodo")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) GetTodos(ctx go_context.Context) (todos Todos, err *Error, clientErr error) {
	rpcArgs := []any{}
	rpcReply := []any{&todos, &err}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "GetTodos", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call todos.ServiceGoTSRPCProxy GetTodos")
	}
	return
}

func (tsc *HTTPServiceGoTSRPCClient) SetComplete(ctx go_context.Context, ID TodoID, complete bool) (todos Todos, err *Error, clientErr error) {
	rpcArgs := []any{ID, complete}
	rpcReply := []any{&todos, &err}
	rpcErr := tsc.Client.Call(ctx, tsc.URL, tsc.EndPoint, "SetComplete", rpcArgs, rpcReply)
	if rpcErr != nil {
		clientErr = pkg_errors.WithMessage(rpcErr, "failed to call todos.ServiceGoTSRPCProxy SetComplete")
	}
	return
}
